### ISSUE TITLE
Read/Write Functions without Structures

### ISSUE THREAD

**Issue by GanbaruTobi** [memflow/memflow-py#27]
It would be nice to be able to read from memory or write to it.

For example os.read(adress, length).
This way I could for example get a full driver out of the memory.

**Comment by emesare** [comment]
So you can do `os.read(addr, c_ubyte * length)` like how I do it for mapping in pages for the unicorn integration [here](https://github.com/memflow/memflow-py/blob/b74ca191a9064590c786029e3ae8b8614f283f6e/examples/unicorn_integration.py#L73).

Like the unicorn integration example shows you can then call [bytes](https://docs.python.org/3/library/stdtypes.html#bytes) to get a python `Bytes` object, from which you can use however you like.

It should also be noted that Structures are not necessary! All primitive types can be found [here](https://github.com/memflow/memflow-py/blob/b74ca191a9064590c786029e3ae8b8614f283f6e/python/memflow/__init__.py#L101).

**Comment by GanbaruTobi** [comment]
Oh, thats great =)
Thank you
